### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sevbo2003** [trivonse/quantic-figma#15]
Website not working
![image](https://user-images.githubusercontent.com/94049540/211192141-cac04225-8b66-41a3-aaaa-94e57c0a2d3f.png)

**Comment by trivonse** [comment]
working bro,check out https://tts-uz.vercel.app

**Comment by jamik-dev** [comment]
working bro,check out https://tts-uz.vercel.app

**Comment by sevbo2003** [comment]
**Yes**, now working well
